### ISSUE TITLE
Requests for non-existent pages should trigger a 404 response

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dpul#849] opened 2020-10-23 17:31 UTC
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/68152643)

**Comment by tpendragon** [comment] 2021-11-12 20:35
Closed as duplicate of #1200

**Closed by tpendragon** 2021-11-12 20:35 UTC
Labels: enhancement, honeybadger, maintenance / research
