### ISSUE TITLE
Content of scope notes not searchable

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#909] opened 2021-05-18 20:06 UTC
"As a user, when I search for content in the scope notes of the MVWs for Grounds and buildings and Historic Postcards, I do not find everything I know to be there or I find nothing at all"

Collections: https://dpul.princeton.edu/pudl0009 AND https://dpul.princeton.edu/ac111 
Examples:
1. Labor gang (in description of scopenote) does not come up in a search, but it is certainly in the description (see screenshot below)
![Screen Shot 2021-05-18 at 4 02 35 PM](https://user-images.githubusercontent.com/45043014/118716292-a994c500-b7f2-11eb-897e-18ab538335cf.png)
2. Elizabeth Menzies (Menzies, Elizabeth G.C.): two items come up when searched, but Phoebe says there are many more of hers, listed as photographer, that are not caught. i have not yet looked myself, but she is sending along examples.

Is this another search bug? Or is this a mapping issue from Figgy/DB to DPUL like we had for WA? because the stuff not searching well is from the item level metadata in the scope notes, I am not sure how that works.

**Comment by kelea99** [comment] 2021-05-19 15:25
Phoebe kindly supplied a document for us! https://docs.google.com/document/d/16Ah0yDuNBQSo3Bjn6GxBr2dkhb7ZqiMe7B73ZvcAMFw/edit?ts=60a52460

**Comment by escowles** [comment] 2021-05-19 15:27
I suspect the problem here is that the metadata from the child volumes of MVWs isn't indexed (and I notice the value in question here is in the `description` field, not in the `metadata` hash).

**Comment by kelea99** [comment] 2021-05-19 15:32
So would this be a "add the metadata for description elsewhere" issue, or is this something that would be solved with indexing? I would not think so?

**Comment by kelea99** [comment] 2021-05-19 15:35
an interesting elaboration from stakeholders: _the one thing I would clarify is that I think DPUL *is* searching the item-level metadata in Postcards more consistently, or at least I did not run into the search issues in Postcards that I did with Grounds._

**Comment by escowles** [comment] 2021-05-19 15:37
Yes, I think this can likely be fixed with indexing, particularly if the issue is that MVW volume metadata is being indexed, but just not the `description` field for whatever reason.

**Comment by escowles** [comment] 2021-05-19 15:42
I looked for an example in the historical postcards, and noticed the word "undivided" in the item metadata for one of the Art Museum postcards. Searching for "undivided" retrieved the Art Museum postcard object (https://dpul.princeton.edu/catalog/9g54xt090). Looking at the metadata, I see that text in the metadata hash under the "abstract" field, instead of the top-level `description` field. So updating the indexing to also index the `description` field would probably fix this. Though we could also just decide to use `abstract` instead, and these would work as-is.

**Comment by tpendragon** [comment] 2021-05-19 15:54
I don't have permission to that document. I can't really dig into this right now, but for reference we only index the metadata hash in the IIIF document if the JSON-LD seeAlso isn't present. So for the postcard example https://figgy.princeton.edu/catalog/c013ae22-efa4-4af1-9072-fc460786aaea.jsonld is what we index.

**Comment by kelea99** [comment] 2021-05-19 15:56
Ideally, standardizing the field used  would be the best way forward (i.e. using the abstract field in lieu of description), especially considering we may have more of these FA with item level descriptions in need of homes (like MC085).  Can you see any downside to this?

**Comment by kelea99** [comment] 2021-05-19 15:56
@tpendragon just changed permissions: https://docs.google.com/document/d/16Ah0yDuNBQSo3Bjn6GxBr2dkhb7ZqiMe7B73ZvcAMFw/edit?usp=sharing

**Comment by tpendragon** [comment] 2021-05-19 16:10
More reference to help figure this issue out:

The individual postcard that returned in @escowles' test comes back because it's indexed and hidden by DPUL in searches, so that its parent returns for any matches it hits: https://dpul.princeton.edu/catalog/tm70mv28c

The example in the document provided isn't indexed in DPUL by itself: https://dpul.princeton.edu/catalog/5h73pw68z

**Comment by hackartisan** [comment] 2022-04-14 20:18
We ended up reingesting these items as just resources (not mvws)

**Closed by hackartisan** 2022-04-14 20:18 UTC
