### ISSUE TITLE
Failing test: Undefined method `should_render_field?`

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#984] opened 2021-09-24 17:48 UTC
Error in Spotlight upgrade:

```
 ActionView::Template::Error:
       undefined method `should_render_field?' for #<Object:0x000055847c9d2e10>
       Did you mean?  should_receive
     # ./app/views/catalog/show.html.erb:1:in `_app_views_catalog_show_html_erb___3554750826893717994_47013732376080'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `should_render_field?' for #<Object:0x000055847c9d2e10>
     #   Did you mean?  should_receive
     #   ./app/views/catalog/show.html.erb:1:in `_app_views_catalog_show_html_erb___3554750826893717994_47013732376080'
```

**Comment by thanyabegum** [comment] 2021-09-24 20:33
Closing as duplicate of #971

**Closed by thanyabegum** 2021-09-24 20:33 UTC
Labels: work-cycle
